
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DISTINTO DIVIDIDO ENTONCES ESCRIBIR IDENTIFICADOR IGUAL IGUALIGUAL LEER LLAVEDER LLAVEIZQ MAS MAYOR MAYORIGUAL MENOR MENORIGUAL MENOS MIENTRAS NUMERO PARENDER PARENIZQ POR PUNTOCOMA SI SINOprograma : sentenciassentencias : sentencias sentencia\n                  | sentenciasentencia : asignacion\n                 | entrada\n                 | salidaasignacion : IDENTIFICADOR IGUAL expresion PUNTOCOMAexpresion : expresion MAS termino\n                 | expresion MENOS terminoexpresion : terminotermino : termino POR factor\n               | termino DIVIDIDO factortermino : factorfactor : NUMEROfactor : IDENTIFICADORentrada : LEER IDENTIFICADOR PUNTOCOMAsalida : ESCRIBIR expresion PUNTOCOMA'
    
_lr_action_items = {'IDENTIFICADOR':([0,2,3,4,5,6,8,9,10,11,19,20,21,22,23,24,25,],[7,7,-3,-4,-5,-6,12,17,-2,17,-16,-17,17,17,17,17,-7,]),'LEER':([0,2,3,4,5,6,10,19,20,25,],[8,8,-3,-4,-5,-6,-2,-16,-17,-7,]),'ESCRIBIR':([0,2,3,4,5,6,10,19,20,25,],[9,9,-3,-4,-5,-6,-2,-16,-17,-7,]),'$end':([1,2,3,4,5,6,10,19,20,25,],[0,-1,-3,-4,-5,-6,-2,-16,-17,-7,]),'IGUAL':([7,],[11,]),'NUMERO':([9,11,21,22,23,24,],[16,16,16,16,16,16,]),'PUNTOCOMA':([12,13,14,15,16,17,18,26,27,28,29,],[19,20,-10,-13,-14,-15,25,-8,-9,-11,-12,]),'MAS':([13,14,15,16,17,18,26,27,28,29,],[21,-10,-13,-14,-15,21,-8,-9,-11,-12,]),'MENOS':([13,14,15,16,17,18,26,27,28,29,],[22,-10,-13,-14,-15,22,-8,-9,-11,-12,]),'POR':([14,15,16,17,26,27,28,29,],[23,-13,-14,-15,23,23,-11,-12,]),'DIVIDIDO':([14,15,16,17,26,27,28,29,],[24,-13,-14,-15,24,24,-11,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'sentencias':([0,],[2,]),'sentencia':([0,2,],[3,10,]),'asignacion':([0,2,],[4,4,]),'entrada':([0,2,],[5,5,]),'salida':([0,2,],[6,6,]),'expresion':([9,11,],[13,18,]),'termino':([9,11,21,22,],[14,14,26,27,]),'factor':([9,11,21,22,23,24,],[15,15,15,15,28,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> sentencias','programa',1,'p_programa','mi_parser.py',9),
  ('sentencias -> sentencias sentencia','sentencias',2,'p_sentencias','mi_parser.py',13),
  ('sentencias -> sentencia','sentencias',1,'p_sentencias','mi_parser.py',14),
  ('sentencia -> asignacion','sentencia',1,'p_sentencia','mi_parser.py',18),
  ('sentencia -> entrada','sentencia',1,'p_sentencia','mi_parser.py',19),
  ('sentencia -> salida','sentencia',1,'p_sentencia','mi_parser.py',20),
  ('asignacion -> IDENTIFICADOR IGUAL expresion PUNTOCOMA','asignacion',4,'p_asignacion','mi_parser.py',26),
  ('expresion -> expresion MAS termino','expresion',3,'p_expresion_operacion','mi_parser.py',30),
  ('expresion -> expresion MENOS termino','expresion',3,'p_expresion_operacion','mi_parser.py',31),
  ('expresion -> termino','expresion',1,'p_expresion_termino','mi_parser.py',38),
  ('termino -> termino POR factor','termino',3,'p_termino_operacion','mi_parser.py',42),
  ('termino -> termino DIVIDIDO factor','termino',3,'p_termino_operacion','mi_parser.py',43),
  ('termino -> factor','termino',1,'p_termino_factor','mi_parser.py',50),
  ('factor -> NUMERO','factor',1,'p_factor_numero','mi_parser.py',54),
  ('factor -> IDENTIFICADOR','factor',1,'p_factor_variable','mi_parser.py',58),
  ('entrada -> LEER IDENTIFICADOR PUNTOCOMA','entrada',3,'p_entrada','mi_parser.py',62),
  ('salida -> ESCRIBIR expresion PUNTOCOMA','salida',3,'p_salida','mi_parser.py',66),
]
